//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace DataBinding.ProdottiServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Prodotto", Namespace="http://tempuri.org/")]
    public partial class Prodotto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string NomeField;
        
        private string NomeCategoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomeCategoria {
            get {
                return this.NomeCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeCategoriaField, value) != true)) {
                    this.NomeCategoriaField = value;
                    this.RaisePropertyChanged("NomeCategoria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProdottiServiceReference.ProdottiServiceSoap")]
    public interface ProdottiServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetProdotti", ReplyAction="*")]
        System.IAsyncResult BeginGetProdotti(DataBinding.ProdottiServiceReference.GetProdottiRequest request, System.AsyncCallback callback, object asyncState);
        
        DataBinding.ProdottiServiceReference.GetProdottiResponse EndGetProdotti(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProdottiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProdotti", Namespace="http://tempuri.org/", Order=0)]
        public DataBinding.ProdottiServiceReference.GetProdottiRequestBody Body;
        
        public GetProdottiRequest() {
        }
        
        public GetProdottiRequest(DataBinding.ProdottiServiceReference.GetProdottiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProdottiRequestBody {
        
        public GetProdottiRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProdottiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProdottiResponse", Namespace="http://tempuri.org/", Order=0)]
        public DataBinding.ProdottiServiceReference.GetProdottiResponseBody Body;
        
        public GetProdottiResponse() {
        }
        
        public GetProdottiResponse(DataBinding.ProdottiServiceReference.GetProdottiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProdottiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<DataBinding.ProdottiServiceReference.Prodotto> GetProdottiResult;
        
        public GetProdottiResponseBody() {
        }
        
        public GetProdottiResponseBody(System.Collections.ObjectModel.ObservableCollection<DataBinding.ProdottiServiceReference.Prodotto> GetProdottiResult) {
            this.GetProdottiResult = GetProdottiResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProdottiServiceSoapChannel : DataBinding.ProdottiServiceReference.ProdottiServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProdottiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProdottiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<DataBinding.ProdottiServiceReference.Prodotto> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<DataBinding.ProdottiServiceReference.Prodotto>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdottiServiceSoapClient : System.ServiceModel.ClientBase<DataBinding.ProdottiServiceReference.ProdottiServiceSoap>, DataBinding.ProdottiServiceReference.ProdottiServiceSoap {
        
        private BeginOperationDelegate onBeginGetProdottiDelegate;
        
        private EndOperationDelegate onEndGetProdottiDelegate;
        
        private System.Threading.SendOrPostCallback onGetProdottiCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ProdottiServiceSoapClient() {
        }
        
        public ProdottiServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdottiServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdottiServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdottiServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetProdottiCompletedEventArgs> GetProdottiCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DataBinding.ProdottiServiceReference.ProdottiServiceSoap.BeginGetProdotti(DataBinding.ProdottiServiceReference.GetProdottiRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProdotti(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetProdotti(System.AsyncCallback callback, object asyncState) {
            DataBinding.ProdottiServiceReference.GetProdottiRequest inValue = new DataBinding.ProdottiServiceReference.GetProdottiRequest();
            inValue.Body = new DataBinding.ProdottiServiceReference.GetProdottiRequestBody();
            return ((DataBinding.ProdottiServiceReference.ProdottiServiceSoap)(this)).BeginGetProdotti(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataBinding.ProdottiServiceReference.GetProdottiResponse DataBinding.ProdottiServiceReference.ProdottiServiceSoap.EndGetProdotti(System.IAsyncResult result) {
            return base.Channel.EndGetProdotti(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<DataBinding.ProdottiServiceReference.Prodotto> EndGetProdotti(System.IAsyncResult result) {
            DataBinding.ProdottiServiceReference.GetProdottiResponse retVal = ((DataBinding.ProdottiServiceReference.ProdottiServiceSoap)(this)).EndGetProdotti(result);
            return retVal.Body.GetProdottiResult;
        }
        
        private System.IAsyncResult OnBeginGetProdotti(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetProdotti(callback, asyncState);
        }
        
        private object[] OnEndGetProdotti(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<DataBinding.ProdottiServiceReference.Prodotto> retVal = this.EndGetProdotti(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProdottiCompleted(object state) {
            if ((this.GetProdottiCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProdottiCompleted(this, new GetProdottiCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProdottiAsync() {
            this.GetProdottiAsync(null);
        }
        
        public void GetProdottiAsync(object userState) {
            if ((this.onBeginGetProdottiDelegate == null)) {
                this.onBeginGetProdottiDelegate = new BeginOperationDelegate(this.OnBeginGetProdotti);
            }
            if ((this.onEndGetProdottiDelegate == null)) {
                this.onEndGetProdottiDelegate = new EndOperationDelegate(this.OnEndGetProdotti);
            }
            if ((this.onGetProdottiCompletedDelegate == null)) {
                this.onGetProdottiCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProdottiCompleted);
            }
            base.InvokeAsync(this.onBeginGetProdottiDelegate, null, this.onEndGetProdottiDelegate, this.onGetProdottiCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override DataBinding.ProdottiServiceReference.ProdottiServiceSoap CreateChannel() {
            return new ProdottiServiceSoapClientChannel(this);
        }
        
        private class ProdottiServiceSoapClientChannel : ChannelBase<DataBinding.ProdottiServiceReference.ProdottiServiceSoap>, DataBinding.ProdottiServiceReference.ProdottiServiceSoap {
            
            public ProdottiServiceSoapClientChannel(System.ServiceModel.ClientBase<DataBinding.ProdottiServiceReference.ProdottiServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetProdotti(DataBinding.ProdottiServiceReference.GetProdottiRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetProdotti", _args, callback, asyncState);
                return _result;
            }
            
            public DataBinding.ProdottiServiceReference.GetProdottiResponse EndGetProdotti(System.IAsyncResult result) {
                object[] _args = new object[0];
                DataBinding.ProdottiServiceReference.GetProdottiResponse _result = ((DataBinding.ProdottiServiceReference.GetProdottiResponse)(base.EndInvoke("GetProdotti", _args, result)));
                return _result;
            }
        }
    }
}
